version: '3.2'
services:

  db:
    image: mysql:5.7
    container_name: debt_tracker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "3306:3306"
    labels:
      - traefik.enable=true
      - traefik.http.routers.debt_mysql.rule=Host(`${DOMAIN_MYSQL}`)
      - traefik.http.routers.debt_mysql.entrypoints=websecure
      - traefik.http.routers.debt_mysql.tls=true
      - traefik.http.routers.debt_mysql.tls.certresolver=le
      - traefik.http.services.debt_mysql.loadbalancer.server.port=3306
    volumes:
      - dbdata:/var/lib/mysql
    networks: 
      - proxy
      - internal
  server:
    container_name: debt_tracker_server
    restart: "always"
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.server
    volumes:
      - ./db:/server/app/db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
    depends_on:
      - db
    networks: 
      - internal
      - bridge

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: debt_tracker_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
#    ports:
#      - 8080:80
    networks:
      - internal
      - proxy
      - exposed
    labels:
      - traefik.enable=true
      - traefik.http.routers.debt_phpmyadmin.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.debt_phpmyadmin.entrypoints=websecure
      - traefik.http.routers.debt_phpmyadmin.tls=true
      - traefik.http.routers.debt_phpmyadmin.tls.certresolver=le
      - traefik.http.services.debt_phpmyadmin.loadbalancer.server.port=80

volumes:
  dbdata:
networks:
  proxy:
    external: true
  internal: 
    internal: true
  exposed:
  bridge:
    driver: bridge
